import type { Metadata } from "next";

import 'bootstrap/dist/css/bootstrap.css';
import "./globals.css";
import  Navbar  from "./ui/navbar";




export const metadata: Metadata = {
  title: "ADAM MESSAADIA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body >
        <div className="bg">
        <Navbar />
        {children}
        </div>
        </body>
    </html>
  );
}
